name: Codecov

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setting up NodeJS
              uses: actions/setup-node@v1

            - name: Setting up nyc
              run: npm i -g nyc

            - name: Clean Install
              run: npm ci

            - name: Coverage
              run: npm run coverage

            - name: Generate Report
              run: nyc report --reporter=text-lcov > coverage.lcov

            - name: Upload Coverage Report
              uses: codecov/codecov-action@v2
